# Job definitions for the Quiet protocol
# Jobs run periodically based on frequency_ms

jobs:
  # Sync with peers to exchange events
  - name: sync_with_peers
    command: create_sync_request
    frequency_ms: 3000  # Every 3 seconds
    params:
      # These will be filled at runtime based on context
      network_id: "{network_id}"
      peer_id: "{peer_id}"
      user_id: "{user_id}"

  # Clean up expired transit secrets
  - name: cleanup_transit_secrets
    command: cleanup_expired_secrets
    frequency_ms: 60000  # Every minute
    params:
      ttl_ms: 30000  # Remove secrets older than 30 seconds

  # Broadcast our address periodically
  - name: announce_address
    command: announce_address
    frequency_ms: 30000  # Every 30 seconds
    params:
      network_id: "{network_id}"
      peer_id: "{peer_id}"
      ip: "{local_ip}"
      port: 5000

  # Check for stale peers (haven't synced recently)
  - name: check_stale_peers
    command: check_peer_staleness
    frequency_ms: 10000  # Every 10 seconds
    params:
      stale_threshold_ms: 30000  # Consider stale after 30 seconds